### ISSUE TITLE
Need to move 'flutter config' from linux build script to image startup script.

### ISSUE THREAD

**Issue by dileeps861** [google/taqo-paco#128]
For linux CI build process, the command `flutter config --enable-linux-desktop` should be configured in custom gcp image. However, as of now it is in linux CI build script, need to move it to image startup script but the process doesn't seem to be trivial and needs further investigation.
#### Workarounds already tried
- Tried setting `flutter config --enable-linux-desktop` as root user in `startup.sh` script of custom gcp ubuntu image. But it still did not enable the linux desktop config at the time linux build script execution.
- `sudo -u ${KOKORO_USER} "flutter config --enable-linux-desktop"`. However this halted the image creation process and image creation vm did not power off.
- `sudo su -c "flutter config --enable-linux-desktop"`. This also halted the image creation process and image creation vm did not power off.
- `sudo su -  ${KOKORO_USER}  "flutter config --enable-linux-desktop"`. For this also image creation vm did not power off. Upon manual power off still config was not enabled and received `"build linux" is not currently supported. To enable, run "flutter config --enable-linux-desktop"`.
- `sudo su -  ${KOKORO_USER} ` 
  `flutter config --enable-linux-desktop`. Same issue as above point.

**Comment by rundong08** [comment]
Done.
