### ISSUE TITLE
Outside collaborations

### ISSUE THREAD

**Issue by shatanikmahanty** [google/taqo-paco#137]
I couldn't find a contributors guideline. Is this repo open for outside Collaborations?

**Comment by rundong08** [comment]
Hi Shatanik,

Thanks for opening this issue!

We welcome outside contributions. Please see https://github.com/google/taqo-paco/blob/develop/docs/contributing.md for the contributing guideline and https://github.com/google/taqo-paco/blob/develop/docs/code-of-conduct.md for code of conduct. 

For coding style, we follow [Dart's official style guide](https://dart.dev/guides/language/effective-dart) for Dart  and [Google's coding style guides](https://google.github.io/styleguide/) for other languages.
