### ISSUE TITLE
taqo_client Build failed due to using end of support APIs

### ISSUE THREAD

**Issue by shatanikmahanty** [google/taqo-paco#138]
## Expected Behavior

Build to work properly

## Actual Behavior

Build failing

## Steps to Reproduce the Problem

1. Use latest flutter version
2. Run pub get on project
3. Try to build the flutter project

## Specifications

APIs like FlatButton and Raised Button were deprecated since a long time. As of now they are not supported any more.
Migration Strategy : To use TextButton and Elevated Button in Place

showSnackbar is now part of ScaffoldMessenger Class and thus it is showing error

- Version: 1.3.0
- Platform: All

**Comment by rundong08** [comment]
Hi Shatanik,

Thanks for reporting this issue! Currently we only support building with a specific version of Flutter defined in https://github.com/google/taqo-paco/blob/develop/deps.cfg, which is 2.5.0-6.0.pre. We have plans to migrate to newer versions of Flutter (but not very soon), but we believe that will involve a lot more than migrating one or two widgets/packages. And thanks for the migration tips. We will have that in mind during migration.
