### ISSUE TITLE
Taqo Linux: Click actions in other notifications will crash the Taqo server

### ISSUE THREAD

**Issue by rundong08** [google/taqo-paco#156]
## Expected Behavior
Click actions in other notifications will not affect Taqo

## Actual Behavior
Click actions in other notifications will crash the Taqo server

## Steps to Reproduce the Problem
1. Start Taqo Server on Linux
2. Generate a notification using
```
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify Taqo 0 '' title click '["default", "Other action", ""]' '{"urgency": <byte 2>}' 0
```
3. Click "Other action" in the pop-up notification
4. Then Taqo serve will crash

**Comment by BobEvans** [comment]
Cannot reproduce on Gnome glinux. Was it a different window manager?

**Comment by rundong08** [comment]
On xfce4, if I click the "Other action" button of the notification, it will crash the Taqo server. If I click elsewhere of the notification to dismiss the notification, nothing will happen.

**Comment by BobEvans** [comment]
Thanks. I will try xfce4.

That worked! I can see the error.

**Comment by rundong08** [comment]
It seems to be xfce4 only... I also tested on gnome and i3 and they seem not having the issue...

**Comment by BobEvans** [comment]
This bug is fixed. Opening a new bug for the problem of glinux gnome not receiving notifications.
