### ISSUE TITLE
Timestamps are not accurate enough for shell and desktop tracers

### ISSUE THREAD

**Issue by rundong08** [google/taqo-paco#221]
Currently all timestamps are only accurate to the second. This may not be enough for the shell tracer since many commands finishes in less than 1 second and it may be confusing when sorting.

We need to improve the accuracy to at least milliseconds.

**Comment by BobEvans** [comment]
Recording your idea from our earlier discussion, we could add a timestamp into the event's outputs that records a higher-fidelity timestamp as a stop-gap measure.

**Comment by rundong08** [comment]
#225 fixed the timestamp for the tracers. Other events may still get less accurate timestamps, but currently accurate timestamps are not essential for other type of events.
